name: Basic Page
type: Starshot
description: 'Provides a basic Page content type with pretty URLs, moderation, scheduling, translation, and meta tags.'
recipes:
  - starshot_content_type_base
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.page:
          - basic
          - advanced
          - open_graph
