name: Admin Theme
type: Starshot
description: Sets up a nice administrative theme and navigation.
install:
  - coffee
  - gin
  - gin_toolbar
  - navigation
config:
  import:
    gin: '*'
    navigation: '*'
  actions:
    gin.settings:
      simple_config_update:
        high_contrast_mode: true
        accent_color: ''
        focus_color: ''
    system.theme:
      simple_config_update:
        admin: gin
