name: Basic HTML editor
type: Starshot
description: 'Enhances the Basic HTML editor with better linking and media support.'
install:
  - ckeditor5
  - linkit
  - media_library
config:
  import:
    linkit:
      - image.style.linkit_result_thumbnail
  actions:
    user.role.authenticated:
      grantPermission: 'use text format basic_html'
