name: Blog
type: Starshot
description: 'Sets up a basic blog, with tagging and commenting.'
recipes:
  - core/recipes/comment_base
  - starshot_anti_spam
  - starshot_content_type_base
  - starshot_image_media_type
  - core/recipes/tags_taxonomy
  - notify_new_comments
config:
  import:
    image:
      # Only import config which is also imported by the Standard profile.
      - image.style.medium
      - image.style.thumbnail
      - image.style.wide
    taxonomy:
      - views.view.taxonomy_term
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.blog:
          - basic
          - advanced
          - open_graph
