name: Accessibility
type: Starshot
description: 'Sets up accessibility tools and functionality.'
recipes:
  - starshot_admin_theme
install:
  - a11y_form_helpers
  - block_aria_landmark_roles
  - editoria11y
config:
  actions:
    gin.settings:
      simple_config_update:
        high_contrast_mode: true
        accent_color: ''
        focus_color: ''
    editoria11y.settings:
      simple_config_update:
        ignore_elements: '.leaflet-map-pane *'
    block.block.olivero_welcome_to_starshot:
      setThirdPartySetting:
        module: block_aria_landmark_roles
        key: role
        value: complimentary
