name: 'Content type basics'
type: 'Starshot'
description: 'Provides basic infrastructure for moderation, meta tags, cloning, previewing, and scheduled publishing of content.'
recipes:
  - core/recipes/editorial_workflow
install:
  - diff
  - metatag
  - metatag_open_graph
  - node
  - pathauto
  - quick_node_clone
  - same_page_preview
  - scheduler
  - simple_sitemap
  - views
config:
  import:
    language: '*'
    metatag:
      - metatag.metatag_defaults.global
      - metatag.metatag_defaults.node
    node:
      # Only import config which is also imported by the Standard profile.
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.rss
      - core.entity_view_mode.node.teaser
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
    simple_sitemap: '*'
    scheduler:
      - views.view.scheduler_scheduled_content
  actions:
    scheduler.settings:
      simple_config_update:
        hide_seconds: true
